[package]
name = "medullah-web"
version = "0.3.12"
edition = "2021"
repository = "https://github.com/spiralover/medullah-web"

publish = ["spiralindex"]

[features]
default = ["feat-mailer", "r2d2"]
feat-database = ["diesel", "r2d2", 'sha2']
feat-rabbitmq = ["lapin"]
feat-base64 = ["base64"]
feat-hmac = ["hmac", 'hex']
feat-nerve = ["reqwest"]
feat-mailer = ["reqwest", "feat-templating"]
feat-crypto = ["rust-argon2", "jsonwebtoken"]
feat-regex = ["fancy-regex"]
feat-validator = ["validator"]
feat-templating = ["tera"]
feat-id-generator = ["nanoid"]
feat-ntex = ["feat-database", "ntex", "ntex-cors"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lapin = { version = "2.3.4", optional = true, default-features = false }
toml = { version = "0.8.14", default-features = false }
uuid = { version = "1.9.1", features = ["serde"], default-features = false }
log = { version = "0.4.22" }
mobc = { version = "0.8.4", features = ["tokio"], default-features = false }
redis = { version = "0.25.4", default-features = false, features = ["arc-swap", "tokio-native-tls-comp"] }
serde = { version = "1.0.203", features = ["serde_derive"], default-features = false }
tokio = { version = "1.38.0" }
chrono = { version = "0.4.38", default-features = false }
dotenv = { version = "0.15.0" }
env_logger = { version = "0.11.3", default-features = false }
chrono-tz = { version = "0.9.0", default-features = false }
serde_json = { version = "1.0.120" }
futures-util = { version = "0.3.30", default-features = false }
base64 = { version = "0.22.1", optional = true, default-features = false }
dyn-clone = { version = "1.0.17" }
hex = { version = "0.4.3", optional = true }
sha2 = { version = "0.10.8", optional = true, default-features = false }
hmac = { version = "0.12.1", optional = true }
fancy-regex = { version = "0.13.0", optional = true, default-features = false }
rust-argon2 = { version = "2.1.0", optional = true }
tera = { version = "1.20.0", optional = true, features = ["chrono"], default-features = false }
nanoid = { version = "0.4.0", optional = true }
ntex = { version = "2.0.3", optional = true, default-features = false }
ntex-multipart = { version = "2.0.0", optional = true }
r2d2 = { version = "0.8.10", optional = true }
ntex-cors = { version = "2.0.0", optional = true }
reqwest = { version = "0.12.4", features = ["json"], optional = true, default-features = false }
diesel = { version = "2.2.1", features = ["postgres", "r2d2", "uuid", "chrono", "serde_json"], optional = true }
jsonwebtoken = { version = "9.3.0", optional = true }
validator = { version = "0.18.1", features = ["derive"], optional = true }
